custom_categories:
    - name: Endpoints
      children:
          - Endpoint
          - BaseURLEndpoint
          
    - name: Type Erasure
      children:
        - AnyEndpoint
        - AnyBaseURLEndpoint
    
    - name: Providers
      children:
        - BodyProvider
        - HeaderFieldsProvider
        - MethodProvider
        - QueryItemsProvider
        - RelativeURLStringProvider
        - URLProvider
        
    - name: HTTP Data
      children:
        - HTTPBody
        - Data
        - InputStream

    - name: HTTP Methods
      children:
        - Method