custom_categories:
    - name: Endpoint Types
      children:
          - EndpointType
          - BaseURLEndpointType
          
    - name: Type Erasure
      children:
        - AnyEndpoint
        - AnyBaseURLEndpoint
    
    - name: Provider Types
      children:
        - BodyProviderType
        - HeaderFieldsProviderType
        - MethodProviderType
        - QueryItemsProviderType
        - RelativeURLStringProviderType
        - URLProviderType
        
    - name: Body Data
      children:
        - BodyType
        - NSData
        - NSInputStream

    - name: HTTP Methods
      children:
        - Method