language: objective-c
xcode_project: Endpoint.xcodeproj
xcode_scheme: Endpoint-OSX
osx_image: xcode8.1
before_install: true
install: true
git:
  submodules: false
script:
  - xcodebuild -project Endpoint.xcodeproj -scheme Endpoint-OSX build test
